export const ALL_POSTS_REQUEST = "ALL_POSTS_REQUEST";
export const ALL_POSTS_SUCCESS = "ALL_POSTS_SUCCESS";
export const ALL_POSTS_FAIL = "ALL_POSTS_FAIL";
export const ALL_POSTS_CLEAR = "ALL_POSTS_CLEAR";

export const GET_POSTS_BY_CATEGORY_REQUEST = "GET_POSTS_BY_CATEGORY_REQUEST";
export const GET_POSTS_BY_CATEGORY_SUCCESS = "GET_POSTS_BY_CATEGORY_SUCCESS";
export const GET_POSTS_BY_CATEGORY_FAIL = "GET_POSTS_BY_CATEGORY_FAIL";

export const ALL_Trending_POSTS_REQUEST = "ALL_Trending_POSTS_REQUEST";
export const ALL_Trending_POSTS_SUCCESS = "ALL_Trending_POSTS_SUCCESS";
export const ALL_Trending_POSTS_FAIL = "ALL_Trending_POSTS_FAIL";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAIL = "LIKE_FAIL";
export const RESET_REACTION = "RESET_REACTION";
export const RESET_ERROR = "RESET_ERROR";

export const AUTHOR_POPULAR_POSTS_REQUEST = "AUTHOR_POPULAR_POSTS_REQUEST";
export const AUTHOR_POPULAR_POSTS_SUCCESS = "AUTHOR_POPULAR_POSTS_SUCCESS";
export const AUTHOR_POPULAR_POSTS_FAIL = "AUTHOR_POPULAR_POSTS_FAIL";

export const RELATED_POSTS_REQUEST = "RELATED_POSTS_REQUEST";
export const RELATED_POSTS_SUCCESS = "RELATED_POSTS_SUCCESS";
export const RELATED_POSTS_FAIL = "RELATED_POSTS_FAIL";
